name: Rust

on:
  push:
    branches: [master]
  pull_request:

env:
  AWS_ACCESS_KEY_ID: test
  AWS_SECRET_ACCESS_KEY: test
  BUCKET: s3-mpu
  CARGO_TERM_COLOR: always
  ENDPOINT: http://localhost:4566

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        target:
        - x86_64-unknown-linux-gnu
        - x86_64-unknown-linux-musl
        dependency-versions:
        - minimal
        - maximum
    steps:
    - uses: actions/checkout@v2
    - if: matrix.target == 'x86_64-unknown-linux-musl'
      run: sudo apt-get install --no-install-recommends --yes musl-tools
    - if: matrix.dependency-versions == 'minimal'
      run: |
        rustup toolchain add nightly
        cargo +nightly update -Z minimal-versions
        # https://github.com/rusoto/rusoto/pull/1925
        cargo update --package async-trait --precise 0.1.9
        cargo update --package percent-encoding --precise 2.1.0
        cargo update --package serde --precise 1.0.103
    - run: rustup target add ${{ matrix.target }}
    - run: cargo build --verbose --target ${{ matrix.target }} --all-targets
    - run: |
        docker run --detach --env SERVICES=s3 --name localstack --publish 4566:4566 localstack/localstack:0.12.10
        until curl --head ${ENDPOINT}/health; do sleep 5; done
        docker exec localstack awslocal s3 mb s3://${BUCKET}
    - run: cargo test --verbose --target ${{ matrix.target }}
  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - run: cargo fmt --verbose -- --check
    - run: cargo clippy --all-targets
